export const LEAGUE = {
  name: 'Top of the Falls',
  shortName: 'TOTF',
  tagline: 'Great Falls Pool Challenge List',
  region: 'Great Falls, MT',
  facebookPageName: 'Top of the Falls Facebook page',
  sponsorBars: ['Silver Spur', 'Lido', 'Black Eagle Country Club'],
  envelopeDropLocations: ['Silver Spur', 'Lido', 'Black Eagle Country Club'],
  matchFeePerPlayer: 5,
  challengeResponseHours: 48,
  matchPlayDays: 10,
  weeklyChallengeLimit: 2,
  lowerSeedWinCooldownHours: 24,
  schedulingWashCooldownHours: 24,
  lossCooldownDays: 7,
  inactiveDropSpots: 2,
  inactiveReviewDays: 30,
  inactiveRemovalReviewDays: 90,
  minRace: 6,
  disciplines: [
    { value: '8 Ball', emoji: '🎱', desc: 'BCA rules · magic rack allowed' },
    { value: '9 Ball', emoji: '🔵', desc: 'Modified BCA · call the 9 · no magic rack' },
    { value: '10 Ball', emoji: '🟡', desc: 'Pro call-shot rules · magic rack allowed' },
    { value: 'Saratoga', emoji: '🎯', desc: 'Allowed for Top 20 matches only' },
  ],
  rulesSummary: [
    'Challenge one spot up in the Top 11; spots 12+ may challenge up to two spots when eligible.',
    'Only #11 and #12 can challenge #10.',
    'The challenged player must respond within 48 hours.',
    'Accepted matches must be played within 10 days unless Top of the Falls approves an exception.',
    'Challenger chooses game and race; both players agree on time and place; challenged player picks table.',
    'All callouts and results must be posted to the Top of the Falls Facebook page with the player tagged.',
    'Match fee is $5 per player in a properly filled envelope.',
    'If the challenged player declines or cannot play, the challenger gets the spot.',
    'If both players offer times but cannot agree, the match is a wash and the challenger sits for 24 hours.',
    'If you defend your spot, include your next challenge with your result to lock it in immediately.',
    'If the lower seed wins, including by forfeit, they wait 24 hours before challenging up again.',
    'If you lose, you must defend or wait 7 days before challenging up.',
    'Inactive players drop two spots every 30 days and can be removed at admin discretion after 90 days.',
    'Top of the Falls has final say on all rules. Rules subject to change.',
  ],
  colors: {
    accent: '#16A34A',
    accentHover: '#22C55E',
    accentDeep: '#14532D',
    accentSoft: 'rgba(22,163,74,0.12)',
  },
} as const;

export type LeagueDiscipline = typeof LEAGUE.disciplines[number]['value'];
export type LeagueVenue = typeof LEAGUE.sponsorBars[number];
