export const LEAGUE = {
  name: 'Top of the Falls',
  shortName: 'TOTF',
  tagline: 'Great Falls Pool Challenge List',
  region: 'Great Falls, MT',
  facebookPageName: 'Top of the Falls Facebook page',
  contact: 'Carl Higgins',
  sponsorBars: ['Silver Spur', 'Lido', 'Black Eagle Country Club'],
  envelopeDropLocations: ['Silver Spur', 'Lido', 'Black Eagle Country Club'],
  matchFeePerPlayer: 5,
  challengeResponseHours: 48,
  matchPlayDays: 10,
  weeklyChallengeLimit: 2,
  lowerSeedWinCooldownHours: 24,
  schedulingWashCooldownHours: 24,
  lossCooldownDays: 7,
  inactiveDropSpots: 2,
  inactiveReviewDays: 30,
  inactiveRemovalReviewDays: 90,
  minRace: 6,
  saratogaTopN: 20,
  disciplines: [
    { value: '8 Ball', emoji: '🎱', desc: 'BCA rules · magic rack allowed' },
    { value: '9 Ball', emoji: '🔵', desc: 'Modified BCA · call the 9 · no magic rack' },
    { value: '10 Ball', emoji: '🟡', desc: 'Pro call-shot rules · magic rack allowed' },
    { value: 'Saratoga', emoji: '🎯', desc: 'Allowed for Top 20 matches only' },
  ],
  // Detailed gameplay rules for each discipline (challenger picks the game).
  gameRules: [
    {
      game: '8 Ball',
      rules: [
        'BCA rules.',
        'Magic rack allowed.',
        'Scratch on the break: ball in hand anywhere.',
        'Scratch on the 8 is not a loss — it is ball in hand to your opponent. Exception: if you make the 8 and scratch, it is a loss.',
      ],
    },
    {
      game: '9 Ball',
      rules: [
        'Modified BCA rules.',
        'No magic rack.',
        'The 9 on the break is good in the top two pockets only.',
        'You must call the 9.',
        'No three-foul rule.',
      ],
    },
    {
      game: '10 Ball',
      rules: [
        'Pro "call shot" rules.',
        'Magic rack allowed.',
        'A 10 made early by carom or combo, if called, is not a win — the 10 is spotted and the player continues to shoot.',
        'Rack: 1 at the front, 10 in the middle, the rest random.',
        'No three-foul rule.',
      ],
    },
    {
      game: 'Saratoga',
      rules: [
        'Allowed in the Top 20 only.',
      ],
    },
  ],
  rulesSummary: [
    'You must be approved to enter the list.',
    'All games are rack-your-own. Players lag for the break; the winner breaks unless both players agree otherwise.',
    'First player to challenge gets the first chance.',
    'Top 11: you may challenge one spot up. Spots 12 and below: you may challenge up to two spots, but if no open player is in range and the open player is directly in front of you, you must challenge them or stay open to challenges from behind.',
    'Only #11 and #12 may challenge #10.',
    'The challenged player must respond within 48 hours of the callout.',
    'Accepted matches must be played within 10 days. Exceptions must be approved by Top of the Falls.',
    'The challenger picks the game and the race; both players agree on time and place; the challenged player picks the table.',
    'Two challenges per week — your week starts from your first challenge.',
    'Minimum race to 6, no maximum if both agree. Winner breaks unless both agree to alternate.',
    'Match fee is $5 per player in a properly filled envelope.',
    'Saratoga is allowed in the Top 20 only.',
    'Matches are played at Black Eagle Country Club, Silver Spur, or the Lido when possible.',
    'All callouts and results must be posted to the Top of the Falls Facebook page with the player tagged.',
    'If the challenged player declines or cannot play, the challenger gets the spot.',
    'If both players offer times but cannot agree, the match is a wash and the challenging player sits for 24 hours. The challenged player may challenge up immediately if no challenge is waiting on their spot.',
    'If you defend your spot, include your next challenge with your result to lock it in immediately — otherwise you are open to challenges from behind until you do.',
    'If the lower seed wins, including by forfeit, they wait 24 hours before challenging up.',
    'If you lose, you must defend or wait 7 days before challenging up.',
    'Players may go inactive anytime. Inactive more than 30 days drops you two spots for every 30 days inactive. On return you must defend or wait 7 days before challenging up (the last player on the list waits 24 hours). Inactive players are reviewed every 30 days and may be removed at admin discretion after 90 days of no engagement.',
    'Questions? Contact Carl Higgins. Top of the Falls has final say on all rules. Rules subject to change.',
  ],
  colors: {
    accent: '#16A34A',
    accentHover: '#22C55E',
    accentDeep: '#14532D',
    accentSoft: 'rgba(22,163,74,0.12)',
  },
} as const;

export type LeagueDiscipline = typeof LEAGUE.disciplines[number]['value'];
export type LeagueVenue = typeof LEAGUE.sponsorBars[number];
