-- TOF bootstrap note: security_and_rank_shift_updates was a recovered pre-schema TOC migration.
-- It is intentionally a no-op in the TOF repo because the canonical recovered base schema starts at 20260321032528.
-- Keeping this version as no-op preserves migration ordering for clean white-label resets without referencing tables before they exist.
