-- TOF bootstrap note: old TOC 1 / Helena seed data intentionally disabled.
-- Do not seed TOC 1 players into TOF or future white-label projects.
-- Customer rosters should be seeded by customer-specific scripts/migrations after schema setup.
